[package]
name = "merkle_mountain_range"
version = "0.1.0"
authors = ["Scott Thorpe <sthorpe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1.25"
leveldb = "0.8"
tempdir = "0.3.7"
